// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKnLDVbZwmuJYY6RhKSh53CjdUsZ3z6Ao',
    appId: '1:266908545911:web:1d8820bfaa6526a52e6772',
    messagingSenderId: '266908545911',
    projectId: 'coins-d394b',
    authDomain: 'coins-d394b.firebaseapp.com',
    storageBucket: 'coins-d394b.appspot.com',
    measurementId: 'G-7FJVH3T0HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ZNB9GmX0q1g78du43cmtiFV_G21k6-U',
    appId: '1:266908545911:android:63a56e4fe524d4792e6772',
    messagingSenderId: '266908545911',
    projectId: 'coins-d394b',
    storageBucket: 'coins-d394b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_NCIJCYkPyxxgwA0KrVoyHyCC3w5MY3E',
    appId: '1:266908545911:ios:bf6d493a6f9d3b252e6772',
    messagingSenderId: '266908545911',
    projectId: 'coins-d394b',
    storageBucket: 'coins-d394b.appspot.com',
    iosBundleId: 'com.example.phones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_NCIJCYkPyxxgwA0KrVoyHyCC3w5MY3E',
    appId: '1:266908545911:ios:3e1eb03108adef252e6772',
    messagingSenderId: '266908545911',
    projectId: 'coins-d394b',
    storageBucket: 'coins-d394b.appspot.com',
    iosBundleId: 'com.example.phones.RunnerTests',
  );
}
